# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
# TODO: This format file is obsolete, consider migrating to JSON.

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "SharpZipLib";
    version = "1.4.2";
    hash = "sha256-/giVqikworG2XKqfN9uLyjUSXr35zBuZ2FX2r8X/WUY=";
  })
]
